@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' === Context Level ===
title System Context Diagram for Sustainable Food Supply Chain

System(certification_body, "Certification System", "Entity responsible for certifying carbon credits and emissions")
Person(user, "User", "Stakeholders in the food supply chain (eg, Az.Agricola, Az.Trasportatrice, Az.DiTrasformazione, Venditori)")

System(system, "Sustainable Food Supply Chain system", "Manages carbon credits") 
' , NFTs, and tracks supply chain activities

Rel(user, system, "Interacts with")
Rel(certification_body, system, "Certifies carbon credits and emissions")

' === Container Level ===
title Container Diagram for Sustainable Food Supply Chain System

Container(frontend, "Frontend application", "TypeScript: React", "Provides a user interface for the users")
Container(backend, "Backend service", "TypeScript", "Handles business logic and interacts with the blockchain")
Container(database, "Relational database", "MySQL", "Stores off-chain data (user info, supply chain metadata)")
Container(blockchain, "Blockchain network", "Hyperledger Besu", "Manages carbon credits (FTs), NFTs, and smart contracts")

Rel(user, frontend, "Uses")
Rel(frontend, backend, "Sends requests to")
Rel(backend, database, "Reads/Writes data to")
Rel(backend, blockchain, "Interacts with smart contracts via ethers.js")


@enduml